# Copyright 2024 Bjørn Erik Pedersen
# SPDX-License-Identifier: MIT

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch: off

comment:
  require_changes: true
