on:
  push:
    branches: [main]
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        shell: bash
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
        shell: bash
      - name: Update PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Fmt
        if: matrix.platform != 'windows-latest' # :(
        run: "diff <(gofmt -d .) <(printf '')"
        shell: bash
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        run: staticcheck ./...
      - name: Lint
        run: golint ./...
      - name: Test
        run: go test -race ./... -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@8f6ec407a34d5ec2b33d7d8f7f50279493b5efb4 # v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
